language: node_js
node_js:
- '0.11'
branches:
  only:
  - master
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    branch: master
git:
  depth: 1
env:
  global:
  - secure: p+8GS5MbVbyD3osvdYQD3ByYJWsaJSxyxBuog34eOwn2oFw9x2FZ72PYLBQS4ZlB6Wl6MjpjgsIRetNJs3O0X8Iwgg+U0fVEubvyjU+CioY+fOo87QvFt/GNf9MvrU57oONNos+NkxKTlldSj2Ks0vkAGA4EmqoP+4/E/OqsZJYuytaTBIc8W2nhrZ1fY3Sd59/SOS0OQma9tAzi84uwr4YDhhd7MKkJ5Pqh/9jxQP3kx3v1R1zax7DYI2OvEVb16OP7L8Wu3A74+lOqQYRVcDNePJWxKizkG+FXgy4QRpgjJXYizdjmwIKYPYI1PvTQnb+ZJe1rjXmR4X1XuBiymzFsZGsPJcTjpfiNHX1tD3VguX5ZwEssLcRV1+/OrazMhDO63ei6czXCkHm1R3PT7ZUyDxVvk9josseUfI49iakf9HBwVh+LYbygMHKTmwh2daiMERM6NShHLroANxyTMTptgruJp/VP8TTgeBQNCvACAPazxkR6I/8PSOzcAN1a/1lUWUqq7pxvtg/ItiL82HAfpuvF2mgqlNTuYOXseDgaEy7+kKcsmBVH+FGfFsNJWuFY5+J3KyPuLY2F3WhUPI35Vy4e+ZHX2WXJ44uDaUN2JOyZDIZv1t4ULWm7SmjWEODuDIm511C/DOndd7hzLCXdabkDSMif+QfoHkf0m8I=
  - secure: qrtO0Wrkif9pb60BXE1Oz1K/Tf7bwdbXhv92yB2Ul5lBmYCo/IOuTYPwC+pQSYUDGbXibkqZgPNaRtkgEPQePL9vyPk4mdqw5VPcW/ZBuoEgg2nRR54lFn+J8mWIh+EqEbGIHJfYzQNCXdUSgMKMSf0lAtoDYX9G0XZUrQ1P3cHTzyVdpSc9KlajdcDbqlv2UQAxVRtPkr1N4ENeRjbIXROnw6zhY17mR0wph/OlVj2T1/Ga/SXJtSJMmeyr9MELnj69c6DfKx7DlFRoxOgbuT59IXU2c0t8kdm8QzoUVAKpqKALAnsBcnA3pnBdOgn1ZhV6K3wa5zOybd8JI9+z1pA5knVotIn/5kPlQAzrX+WAUAx4lHXs0IiDke21+xJltiSOFmaho5HfOq8LzXLm88mknAiO4hvaDZqRzqsbZ8YzR76ZzP/UXGKG9JY19EgHN1ri9b8qFx7ydQ3SrkBy/kaS9HXUWqhep8UL/slJZqNuFJhsA2oRwHJrkVob881qZtCtu+dMuyw4HkO7sDy89qGupDKXHC1JhnCfwVQHlo46Rf4cg5BE/WF8d7pNn/WZht+3Bo9ZMpzs53uZrn/fPXanVp1tG5vMU6tPRY3AVll5MD/dl1Nv6De3h0QX0miqOu4b4S8K792OqdquClE6LFrKmRY+IiMHD6jtHA8o5vQ=
  - secure: E513JwowPIAYK/DLln3kZjv3I7F7JrRuLwF4Qa2P//w5e0AoDUeY9ozx2eNuvCon7EdkDRIiXLJ0xfzpKK3NmalS9AtBsivjl1j2xCgB2QYaeCkkEiXu2UyFdsIQgpN6v1eQCffqeZBo7mxh8yDSwu0K+dIyaH+9qCqxqfxHw0cVyevuYy7a6LgEbB6k/BjVx9F2ihLFlquREqZUMiAgVPjQpnT8YEgVmTFUkoawBg6yCO1VVn5CAM5LNwtHhNPYiRUHPu88WBiediNZxE55UhG5lBatZFp2Q0hPXGWohbfhTjQfrqNjtZnNSg53NHp934e14xkMYSDYb3pUqxGI1JFb0mivDcTC51K0V7NPiRnCH5xdVLZCtk9MY9AD+Ar7wCD4g4T5NSzt8/S1+70COF3hsGXGngrwmWc7cGp3cPGiR6WBKfFvNIDTayRfW5nHfDXKp1GXmg1YAfg4iTF5i/IK1njrg5ppTW1k+SSQta0vVSicpP0r3z5zj1OR9OuxcHJQr827ba/be2Yb1tyDZKOWKuxUwosdaJA9MxrfysJOFiTFo+sxnHm/Ndy6jWGdt7JJNF/Wf1X+5yjgwzwFT2PC5Ft1/VltLVSQr45bCUFaHue50qykf2DB72ghVKW2sdra2i1t+i0bzKROw9CkCV/6X1tniRxA0xwsvCMZrlU=
